### ISSUE TITLE
Write a fetch function for RMP professor data

### ISSUE THREAD

**Issue by heartgg** [UTDNebula/skedge#4]
Function(s) location: fetch.ts (at least for now)
Use types and interfaces via Typescript https://blog.logrocket.com/types-vs-interfaces-in-typescript/

Parameters:
- Array of professor names? This will be taken from scraping course scheduler page
- school ID (UTD is 1273)

Output:
- RMP ratings data (Probably array, but I forgot of what)

Refer to:
- https://github.com/demonlexe/sk.edge/blob/main/Extension/fetch.js
- https://github.com/demonlexe/sk.edge/blob/main/Extension/nebula.js

**Comment by quocannguyen** [comment]
I will try this.

**Comment by demonlexe** [comment]
`
import fetch from "node-fetch";

async function fetchWithProfessor(profName) {
    const highRes = await fetch(
        `https://www.ratemyprofessors.com/search/teachers?query=${encodeURIComponent(profName)}&sid=${btoa(`School-1273`)}`
    )
    return await highRes.text();
}



function extractProfessorIdFromSearchResults(request, texts : string[]) {
    // console.log("Extracting professor IDs from search results",texts)
    var profIds : string[] = [];

    texts.forEach(text => {
        console.log(text);
        const regex = /"legacyId":(\d+).*?"firstName":"(\w+)","lastName":"(\w+)"/g;
        for (const match of text.matchAll(regex)) {
            if (request.profNames.includes(match[2] + " " + match[3])) {
                profIds.push(match[1]);
            }
        }
    })
    return profIds;
            
}

let mockRequest = {
    profNames: "Scott Dollinger"
}
let text : string = await fetchWithProfessor(mockRequest.profNames);
let ids : string[] = extractProfessorIdFromSearchResults(mockRequest, [text]);

console.log("IDs are " + ids);`

**Comment by demonlexe** [comment]
[codeStarteed.zip](https://github.com/UTDNebula/skedge/files/10845275/codeStarteed.zip)
