### ISSUE TITLE
Fix `Top Tags`

### ISSUE THREAD

**Issue by demonlexe** [UTDNebula/skedge#41]
Looks like these are either hardcoded or not being scraped properly

Displayed data:
<img width="264" alt="image" src="https://github.com/UTDNebula/skedge/assets/84201567/b950bcf1-627d-49a1-9ef0-5a7fabd05f84">

Actual top tags from RMP:
<img width="276" alt="image" src="https://github.com/UTDNebula/skedge/assets/84201567/18eb8f09-c555-40cf-a24f-ac7ce8a5a189">

**Comment by TyHil** [comment]
The top tags were sorted in the wrong order, showing the least reported ones first.
