### ISSUE TITLE
Research: Class-Specific Data

### ISSUE THREAD

**Issue by demonlexe** [UTDNebula/skedge#42]
Would it be nice to have some information on what classes a professor teaches?

Potential ways to get this data:
- Coursebook Scrape
- RMP Scrape. Drawbacks: could be out of date. 
<img width="167" alt="image" src="https://github.com/UTDNebula/skedge/assets/84201567/2a391592-765f-44b9-af0d-2a1b1f62e3c7">

Take the individual professor card for example. We could add a section titled "Taught Courses", with all the courses that the professor teaches.

I.E.
<img width="550" alt="image" src="https://github.com/UTDNebula/skedge/assets/84201567/8c2fc40a-d834-4249-b85d-29b736234225">

**Comment by TyHil** [comment]
This is possible in Trends by searching for the professor, I suggest we keep that functionality just in Trends.
