### ISSUE TITLE
Bugfix: Do not show professors from other schools

### ISSUE THREAD

**Issue by demonlexe** [UTDNebula/skedge#45]
# Description

Take "Alice Wang" for example. There are no reports for her at UTD:

![image](https://github.com/UTDNebula/skedge/assets/84201567/3e6727f1-87ec-4fab-99bc-296fa25f3ac1)

However, we are currently populating with a professor of her name, but not at UTD. Since we cannot confirm that it's the same person, we should decide what to show instead.

![image](https://github.com/UTDNebula/skedge/assets/84201567/cf42513a-ab65-4633-b653-8fec72fe7847)
![image](https://github.com/UTDNebula/skedge/assets/84201567/a225a9a8-64d5-40ae-b5eb-42a9054fa942)

# Solutions

- Could display "No UTD Professor Found. Click *here* for all instances of Alice Wang", which would hyperlink to the https://www.ratemyprofessors.com/search/professors/1273?q=alice%20wang page.

**Comment by TyHil** [comment]
Anyone have a new example of this? Alice Wang seems to exist now in RMP making it hard to recreate and address the problem
