### ISSUE TITLE
Write fetch function to get sections from Nebula API

### ISSUE THREAD

**Issue by heartgg** [UTDNebula/skedge#7]
Function(s) location: fetch.ts (at least for now)
Use types and interfaces via Typescript https://blog.logrocket.com/types-vs-interfaces-in-typescript/

Parameters:
- professor reference (string)
- course reference (string)

Output:
- Array of sections

Refer to https://github.com/demonlexe/sk.edge/blob/main/Extension/fetch.js

**Comment by KimotoNari** [comment]
Working on this
