### ISSUE TITLE
Write fetch function to get Professor data from Nebula API

### ISSUE THREAD

**Issue by heartgg** [UTDNebula/skedge#8]
Function(s) location: fetch.ts (at least for now)
Use types and interfaces via Typescript https://blog.logrocket.com/types-vs-interfaces-in-typescript/

Parameters:
- first name (string)
- last name (string)

Output:
- Professor data (?)

Refer to https://github.com/demonlexe/sk.edge/blob/main/Extension/fetch.js

**Comment by demonlexe** [comment]
I will take this one! Please assign me to this when possible

**Comment by demonlexe** [comment]
Included in my pull request, #12
