### ISSUE TITLE
Write fetch function to get course data from Nebula API

### ISSUE THREAD

**Issue by heartgg** [UTDNebula/skedge#9]
Function(s) location: fetch.ts (at least for now)
Use types and interfaces via Typescript https://blog.logrocket.com/types-vs-interfaces-in-typescript/

Parameters:
- course prefix (string)
- course number (string)

Output:
- Course data (?)

Refer to https://github.com/demonlexe/sk.edge/blob/main/Extension/fetch.js

**Comment by demonlexe** [comment]
I'm doing this issue!

**Comment by demonlexe** [comment]
Included in my pull request, #12
